blkid debug

diff --git a/overlay/initramfs-installer/init b/overlay/initramfs-installer/init
--- a/overlay/initramfs-installer/init
+++ b/overlay/initramfs-installer/init
@@ -16,6 +16,15 @@ mount -t sysfs sysfs /sys
 echo "Exportando bin y sbin"
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
 
+echo "[DEBUG] PATH=$PATH"
+echo "[DEBUG] Verificando blkid"
+command -v blkid || echo "[ERROR] blkid no está en el PATH"
+ls -lh /sbin/blkid || echo "[ERROR] /sbin/blkid no existe"
+ldd /sbin/blkid || echo "[ERROR] Dependencias de blkid no completas"
+
+blkid || echo "[ERROR] blkid falló"
+
+
 echo "Determinando variables del sistema"
 export WOLFBEAR_OS_PRODUCT_NAME=$( cat /sys/class/dmi/id/product_name 2>/dev/null | tr -d '\r' )
 export WOLFBEAR_OS_SYS_VENDOR=$( cat /sys/class/dmi/id/sys_vendor )
